#!/bin/sh

ensureGitleaksInstalled() {
  # Check if gitleaks is installed
  if ! [ -x "$(command -v gitleaks)" ]; then
    echo "gitleaks not found. Installing gitleaks..."
    curl -s https://raw.githubusercontent.com/suhovius/gitleaks-tools/main/install.sh | bash

    if ! type "gitleaks" > /dev/null; then
      echo "Failed to install gitleaks. Aborting commit."
      exit 1
    fi
  fi  
}

runGitleaksProtectCheck() {
  # Run gitleaks protect on the staged changes
  gitleaks protect --verbose --redact --staged

  # Capture the exit status of gitleaks
  status=$?

  if [ $status -ne 0 ]; then
    echo "gitleaks protect found sensitive information. Please review and resolve."
    exit 1
  fi

  echo "gitleaks protect check passed."
}

gitleaksProtectCheck() {
  local check_enabled=$(git config --get --bool hooks.gitleaks.protect)
  if [ ! -z $check_enabled ] && [ $check_enabled == "true" ]; then
    ensureGitleaksInstalled
    runGitleaksProtectCheck
  else
    echo "hooks.gitleaks.protect is not set, skipping gitleaks check."
  fi    
}

runGitleaksDetectCheck() {
  # Run gitleaks detect on the commited changes
  gitleaks detect --verbose --redact

  # Capture the exit status of gitleaks
  status=$?

  if [ $status -ne 0 ]; then
    echo "gitleaks detect found sensitive information. Please review and resolve."
    exit 1
  fi

  echo "gitleaks detect check passed."
}

gitleaksDetectCheck() {
  local check_enabled=$(git config --get --bool hooks.gitleaks.detect)
  if [ ! -z $check_enabled ] && [ $check_enabled == "true" ]; then
    ensureGitleaksInstalled
    runGitleaksDetectCheck
  else
    echo "hooks.gitleaks.detect is not set, skipping gitleaks check."
  fi
}

# Enable the gitleaks protect hook with git config hooks.gitleaks.protect true
# Run gitleaks protect on the staged changes
gitleaksProtectCheck

# Enable the gitleaks detect hook with git config hooks.gitleaks.detect true
# Run gitleaks detect on the commited changes
gitleaksDetectCheck

# INFO: Any additional hooks can be added here keeping the same style to call exit on failure only
# to let all the possible hooks being called.

echo "All pre-commit checks passed."

# Exit with success if no any hooks are enabled or no any of them have failed
exit 0